/* Edit only this file when creating a new startpage. */
window.SITE_CONFIG = {
  name: "Saved",
  domain: "saved",
  url: "https://saved/",
  title: "Saved - Your gateway to the net",
  description: "The ultimate secure home screen to organize your favorite links and tools. Enjoy rapid loading, total confidentiality, and a bespoke interface. Elevate your internet journey.",
  tagline: "Your gateway to the net",

  /* Initial links shown to new visitors. Edit, add, remove or reorder them here. */
  suggestedLinks: [
    { name: "Google Saved", url: "https://www.google.com/interests/saved?authuser=0", color: "#68d8ff", category: "Genel" },
    { name: "Google Products", url: "https://about.google/intl/tr_ALL/products/", color: "#68d8ff", category: "Genel" },
    { name: "Google Search", url: "https://www.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Drive", url: "https://drive.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Docs", url: "https://docs.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Sheets", url: "https://sheets.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Slides", url: "https://slides.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Forms", url: "https://forms.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Calendar", url: "https://calendar.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Keep", url: "https://keep.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Photos", url: "https://photos.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Meet", url: "https://meet.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google News", url: "https://news.google.com/", color: "#ff7b7b", category: "Genel" },
    { name: "Google Play", url: "https://play.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Scholar", url: "https://scholar.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Translate", url: "https://translate.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google", url: "https://www.google.com", color: "#68d8ff", category: "Genel" },
    { name: "Google Lens", url: "https://lens.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google One", url: "https://one.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Contacts", url: "https://contacts.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Fonts", url: "https://fonts.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Google Tasks", url: "https://tasks.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Blogger", url: "https://www.blogger.com/", color: "#ff9e64", category: "Genel" },
    { name: "Gmail", url: "https://mail.google.com/", color: "#68d8ff", category: "Genel" },
    { name: "Yandex", url: "https://yandex.com/", color: "#ff6b6b", category: "Genel" },
    { name: "Vuhuv", url: "https://vuhuv.com/", color: "#ff9e64", category: "Genel" },
    { name: "Biliver", url: "https://www.biliver.com/", color: "#ff9e64", category: "Genel" },
    { name: "Wikipedia", url: "https://www.wikipedia.org", color: "#9cf56a", category: "Genel" },
    { name: "DeepL", url: "https://www.deepl.com", color: "#68d8ff", category: "Genel" },
    { name: "Translate", url: "https://translate.google.com", color: "#68d8ff", category: "Genel" },
    { name: "Photo Search", url: "https://photosearch.tv", color: "#ff7b7b", category: "Genel" },
    { name: "Internet Archive", url: "https://archive.org", color: "#ff9e64", category: "Genel" },
    { name: "Yandex Mail", url: "https://mail.yandex.com.tr", color: "#68d8ff", category: "Genel" },
    { name: "U18.net", url: "https://u18.net", color: "#68d8ff", category: "Genel" },
    { name: "Yandex Translate", url: "https://translate.yandex.com/", color: "#ff6b6b", category: "Genel" },
    { name: "Yandex Disk", url: "https://disk.yandex.com.tr/", color: "#68d8ff", category: "Genel" },
    { name: "Yandex Video", url: "https://yandex.com/video/", color: "#ff6b6b", category: "Genel" },
    { name: "Yandex Calendar", url: "https://calendar.yandex.com/", color: "#ff6b6b", category: "Genel" },
    { name: "mail.com.tr", url: "https://mail.com.tr", color: "#68d8ff", category: "Genel" },
    { name: "Türk Telekom", url: "https://www.turktelekom.com.tr", color: "#68d8ff", category: "Genel" },
    { name: "Yapı Kredi", url: "https://www.yapikredi.com.tr", color: "#ff7898", category: "Genel" },
    { name: "Ziraat", url: "https://www.ziraatbank.com.tr", color: "#ff7898", category: "Genel" },
    { name: "Google Chat", url: "https://chat.google.com/", color: "#68d8ff", category: "Sosyal" },
    { name: "Google Messages Web", url: "https://messages.google.com/web/", color: "#70df8e", category: "Sosyal" },
    { name: "Reddit", url: "https://www.reddit.com", color: "#ff9e64", category: "Sosyal" },
    { name: "X", url: "https://x.com", color: "#95a8a2", category: "Sosyal" },
    { name: "Discord", url: "https://discord.com", color: "#d7a0ff", category: "Sosyal" },
    { name: "WhatsApp Web", url: "https://web.whatsapp.com", color: "#70df8e", category: "Sosyal" },
    { name: "Video Chat", url: "https://liveeds.com", color: "#ff6b6b", category: "Sosyal" },
    { name: "Chat", url: "https://worldchat.tv", color: "#70df8e", category: "Sosyal" },
    { name: "Telegram Web", url: "https://web.telegram.org/a/", color: "#68d8ff", category: "Sosyal" },
    { name: "Instagram", url: "https://www.instagram.com/", color: "#ff7898", category: "Sosyal" },
    { name: "Yandex Zen", url: "https://zen.yandex.com/", color: "#ff6b6b", category: "Sosyal" },
    { name: "ok.ru", url: "https://ok.ru/", color: "#ff9e64", category: "Sosyal" },
    { name: "VK", url: "https://vk.com/", color: "#68d8ff", category: "Sosyal" },
    { name: "Ask.fm", url: "https://ask.fm/", color: "#d7a0ff", category: "Sosyal" },
    { name: "Facebook", url: "https://www.facebook.com/", color: "#68d8ff", category: "Sosyal" },
    { name: "YouTube", url: "https://www.youtube.com", color: "#ff7b7b", category: "Medya" },
    { name: "Twitch", url: "https://www.twitch.tv/", color: "#d7a0ff", category: "Medya" },
    { name: "DLive", url: "https://dlive.tv/", color: "#68d8ff", category: "Medya" },
    { name: "Kick", url: "https://kick.com/", color: "#9cf56a", category: "Medya" },
    { name: "Rumble", url: "https://rumble.com/", color: "#ff9e64", category: "Medya" },
    { name: "Odysee", url: "https://odysee.com/", color: "#ff7898", category: "Medya" },
    { name: "Vimeo", url: "https://vimeo.com/", color: "#d7a0ff", category: "Medya" },
    { name: "Dailymotion", url: "https://www.dailymotion.com/", color: "#68d8ff", category: "Medya" },
    { name: "Spotify", url: "https://open.spotify.com", color: "#70df8e", category: "Medya" },
    { name: "Netflix", url: "https://www.netflix.com", color: "#ff7b7b", category: "Medya" },
    { name: "Radio", url: "https://radiobrowser.com", color: "#ff9e64", category: "Medya" },
    { name: "YouTube Music", url: "https://music.youtube.com/", color: "#ff7b7b", category: "Medya" },
    { name: "Yandex Music", url: "https://music.yandex.com/", color: "#ff6b6b", category: "Medya" },
    { name: "YouTube Studio", url: "https://studio.youtube.com/", color: "#ff7b7b", category: "Medya" },
    { name: "IPTVnator Web", url: "https://iptvnator.vercel.app/", color: "#68d8ff", category: "Medya" },
    { name: "HLS.js Demo", url: "https://hlsjs.video-dev.org/demo/", color: "#9cf56a", category: "Medya" },
    { name: "OpenTV Player", url: "https://opentvplayer.com/", color: "#68d8ff", category: "Medya" },
    { name: "StreamingTVGuides", url: "http://player.streamingtvguides.com", color: "#ff9e64", category: "Medya" },
    { name: "M3U8 Play", url: "https://m3u8play.dev", color: "#d7a0ff", category: "Medya" },
    { name: "SS-IPTV", url: "https://www.ss-iptv.com/en/users/playlist", color: "#9cf56a", category: "Medya" },
    { name: "Golden Player", url: "https://play.google.com/store/apps/details?id=com.lamdaticket.goldenplayer", color: "#ff9e64", category: "Medya" },
    { name: "Query-Streamlink", url: "https://github.com/LaneSh4d0w/query-streamlink", color: "#ff7b7b", category: "Medya" },
    { name: "AliExpress", url: "https://tr.aliexpress.com", color: "#ff7b7b", category: "Alışveriş" },
    { name: "Hepsiburada", url: "https://www.hepsiburada.com", color: "#d7a0ff", category: "Alışveriş" },
    { name: "Trendyol", url: "https://www.trendyol.com", color: "#ff9e64", category: "Alışveriş" },
    { name: "Amazon.com.tr", url: "https://www.amazon.com.tr", color: "#ff9e64", category: "Alışveriş" },
    { name: "Yemek Sepeti", url: "https://www.yemeksepeti.com", color: "#ff7898", category: "Alışveriş" },
    { name: "Amazon", url: "https://www.amazon.com", color: "#ff9e64", category: "Alışveriş" },
    { name: "Google My Maps", url: "https://www.google.com/maps/d/edit", color: "#d7a0ff", category: "Konum" },
    { name: "Google Maps", url: "https://maps.google.com/", color: "#68d8ff", category: "Konum" },
    { name: "OpenStreetMap", url: "https://www.openstreetmap.org/", color: "#9cf56a", category: "Konum" },
    { name: "Yandex Maps", url: "https://yandex.com/maps", color: "#ff6b6b", category: "Konum" },
    { name: "Nokta", url: "https://nokta.com/harita", color: "#ff9e64", category: "Konum" },
    { name: "Windy", url: "https://www.windy.com", color: "#68d8ff", category: "Konum" },
    { name: "Bing Harita", url: "https://www.bing.com/maps", color: "#68d8ff", category: "Konum" },
    { name: "Games", url: "https://arcadeok.com", color: "#9cf56a", category: "Oyun" },
    { name: "Prime Gaming", url: "https://gaming.amazon.com/lp/freegames", color: "#68d8ff", category: "Oyun" },
    { name: "GG.deals Freebies", url: "https://gg.deals/deals/freebies/", color: "#d7a0ff", category: "Oyun" },
    { name: "Piano", url: "https://virtualpiano.eu", color: "#d7a0ff", category: "Oyun" },
    { name: "Steam Free Games", url: "https://store.steampowered.com/genre/Free%20to%20Play/", color: "#68d8ff", category: "Oyun" },
    { name: "Epic Free Games", url: "https://store.epicgames.com/en-US/free-games", color: "#d7a0ff", category: "Oyun" },
    { name: "GOG Free Games", url: "https://www.gog.com/en/partner/free_games", color: "#9cf56a", category: "Oyun" },
    { name: "Humble Store", url: "https://www.humblebundle.com/store", color: "#ff7b7b", category: "Oyun" },
    { name: "Xbox Free Games", url: "https://www.xbox.com/en-US/games/free-games", color: "#70df8e", category: "Oyun" },
    { name: "itch.io Free Games", url: "https://itch.io/games/free", color: "#ff7898", category: "Oyun" },
    { name: "IndieGala Freebies", url: "https://freebies.indiegala.com/", color: "#d7a0ff", category: "Oyun" },
    { name: "Free To Keep", url: "https://freetokeep.gg/", color: "#9cf56a", category: "Oyun" },
    { name: "Reddit FreeGameFindings", url: "https://www.reddit.com/r/FreeGameFindings/", color: "#ff9e64", category: "Oyun" },
    { name: "FreeGames.lol", url: "https://freegames.lol/", color: "#68d8ff", category: "Oyun" },
    { name: "IndieBundle Free", url: "https://www.indiegamebundles.com/category/free/", color: "#ff7b7b", category: "Oyun" },
    { name: "EmuOS", url: "https://emupedia.net/beta/emuos/", color: "#68d8ff", category: "Oyun" },
    { name: "Archive Software Library", url: "https://archive.org/details/softwarelibrary", color: "#ff9e64", category: "Oyun" },
    { name: "PlayClassic.Games", url: "https://playclassic.games/", color: "#d7a0ff", category: "Oyun" },
    { name: "RetroGames.cc", url: "https://www.retrogames.cc/", color: "#ff7898", category: "Oyun" },
    { name: "Poki", url: "https://poki.com/", color: "#9cf56a", category: "Oyun" },
    { name: "Unreal Engine", url: "https://www.unrealengine.com", color: "#d7a0ff", category: "Oyun" },
    { name: "Fanatical Free", url: "https://www.fanatical.com/en/free", color: "#68d8ff", category: "Oyun" },
    { name: "Google Trends", url: "https://trends.google.com", color: "#ff9e64", category: "Araçlar" },
    { name: "Google Ads", url: "https://ads.google.com/", color: "#68d8ff", category: "Araçlar" },
    { name: "Tracking", url: "https://trackingcode.net", color: "#ff7b7b", category: "Araçlar" },
    { name: "SpeedTest", url: "https://browserspeed.net", color: "#ff6b6b", category: "Araçlar" },
    { name: "Antivirus", url: "https://freeantivirus.pro", color: "#68d8ff", category: "Araçlar" },
    { name: "Upload", url: "https://deliverbit.com", color: "#9cf56a", category: "Araçlar" },
    { name: "Software", url: "https://rcpsoft.net", color: "#ff9e64", category: "Araçlar" },
    { name: "Apps", url: "https://softenjoy.com", color: "#d7a0ff", category: "Araçlar" },
    { name: "Webmaster", url: "https://internetindexer.com", color: "#68d8ff", category: "Araçlar" },
    { name: "Temp Mail Ninja", url: "https://tempmail.ninja", color: "#68d8ff", category: "Araçlar" },
    { name: "SmallPDF", url: "https://smallpdf.com", color: "#ff7b7b", category: "Araçlar" },
    { name: "Wayback Machine", url: "https://web.archive.org", color: "#ff7b7b", category: "Araçlar" },
    { name: "ShareX", url: "https://getsharex.com", color: "#ff7b7b", category: "Araçlar" },
    { name: "Temp Mail", url: "https://temp-mail.org", color: "#ff7b7b", category: "Araçlar" },
    { name: "TinyURL", url: "https://tinyurl.com", color: "#ff7b7b", category: "Araçlar" },
    { name: "PDFescape", url: "https://www.pdfescape.com", color: "#ff7b7b", category: "Araçlar" },
    { name: "CloudConvert", url: "https://cloudconvert.com", color: "#ff7b7b", category: "Araçlar" },
    { name: "WeTransfer", url: "https://wetransfer.com", color: "#ff7b7b", category: "Araçlar" },
    { name: "Sender", url: "https://www.sender.net", color: "#ff9e64", category: "Araçlar" },
    { name: "Ocoya", url: "https://www.ocoya.com", color: "#ff9e64", category: "Araçlar" },
    { name: "Ubersuggest", url: "https://ubersuggest.com", color: "#ff9e64", category: "Araçlar" },
    { name: "HubSpot", url: "https://www.hubspot.com", color: "#ff9e64", category: "Araçlar" },
    { name: "Designify", url: "https://www.designify.com", color: "#ff9e64", category: "Araçlar" },
    { name: "Buffer", url: "https://buffer.com", color: "#ff9e64", category: "Araçlar" },
    { name: "AnswerThePublic", url: "https://answerthepublic.com", color: "#ff9e64", category: "Araçlar" },
    { name: "Buzzsumo", url: "https://buzzsumo.com", color: "#ff9e64", category: "Araçlar" },
    { name: "Mem.ai", url: "https://mem.ai", color: "#9cf56a", category: "Araçlar" },
    { name: "Trevor AI", url: "https://www.trevorai.com", color: "#9cf56a", category: "Araçlar" },
    { name: "Reclaim.ai", url: "https://reclaim.ai", color: "#9cf56a", category: "Araçlar" },
    { name: "Clockwise", url: "https://www.getclockwise.com", color: "#9cf56a", category: "Araçlar" },
    { name: "Motion", url: "https://www.usemotion.com", color: "#9cf56a", category: "Araçlar" },
    { name: "Yandex Metrica", url: "https://metrika.yandex.com/", color: "#ff6b6b", category: "Araçlar" },
    { name: "Yandex Wordstat", url: "https://wordstat.yandex.com/", color: "#ff6b6b", category: "Araçlar" },
    { name: "Google Colab", url: "https://colab.research.google.com/", color: "#68d8ff", category: "Programlama" },
    { name: "ythls-FastAPI", url: "https://github.com/keyiflerolsun/ythls-FastAPI", color: "#ff7b7b", category: "Programlama" },
    { name: "Stack Overflow", url: "https://stackoverflow.com", color: "#ff9e64", category: "Programlama" },
    { name: "GitHub", url: "https://github.com", color: "#d7a0ff", category: "Programlama" },
    { name: "GeeksforGeeks", url: "https://www.geeksforgeeks.org", color: "#9cf56a", category: "Programlama" },
    { name: "CS50", url: "https://cs50.harvard.edu", color: "#9cf56a", category: "Programlama" },
    { name: "LeetCode", url: "https://leetcode.com", color: "#9cf56a", category: "Programlama" },
    { name: "Exercism", url: "https://exercism.org", color: "#9cf56a", category: "Programlama" },
    { name: "SoloLearn", url: "https://www.sololearn.com", color: "#9cf56a", category: "Programlama" },
    { name: "Programiz", url: "https://www.programiz.com", color: "#9cf56a", category: "Programlama" },
    { name: "freeCodeCamp", url: "https://www.freecodecamp.org", color: "#9cf56a", category: "Programlama" },
    { name: "W3Schools", url: "https://www.w3schools.com", color: "#9cf56a", category: "Programlama" },
    { name: "Codecademy", url: "https://www.codecademy.com", color: "#9cf56a", category: "Programlama" },
    { name: "CodeHype", url: "https://codehype.in", color: "#9cf56a", category: "Programlama" },
    { name: "GitHub Copilot", url: "https://github.com/features/copilot", color: "#9cf56a", category: "Programlama" },
    { name: "Yandex Cloud", url: "https://cloud.yandex.com/", color: "#ff6b6b", category: "Programlama" },
    { name: "DistroSea", url: "https://distrosea.com/", color: "#9cf56a", category: "Programlama" },
    { name: "v86 Emulator", url: "https://copy.sh/v86/", color: "#9cf56a", category: "Programlama" },
    { name: "JSLinux", url: "https://bellard.org/jslinux/", color: "#9cf56a", category: "Programlama" },
    { name: "IPTV-org Database", url: "https://github.com/iptv-org/iptv", color: "#ff7b7b", category: "Programlama" },
    { name: "IPTV-org Awesome", url: "https://github.com/iptv-org/awesome-iptv", color: "#ff7b7b", category: "Programlama" },
    { name: "Legal-IPTV", url: "https://github.com/UzunMuhalefet/Legal-IPTV", color: "#ff7b7b", category: "Programlama" },
    { name: "devsolux Playlist", url: "https://github.com/devsolux/iptv-playlist", color: "#ff7b7b", category: "Programlama" },
    { name: "Kekik M3U", url: "https://github.com/KekikAkademi/m3u-indir", color: "#ff7b7b", category: "Programlama" },
    { name: "IPTV-Proxy", url: "https://github.com/pierre-emmanuelJ/iptv-proxy", color: "#ff7b7b", category: "Programlama" },
    { name: "m3u_parser", url: "https://github.com/pawanpaudel93/m3u_parser", color: "#ff7b7b", category: "Programlama" },
    { name: "ArchWiki", url: "https://wiki.archlinux.org/", color: "#68d8ff", category: "Programlama" },
    { name: "Linux.com", url: "https://www.linux.com/", color: "#9cf56a", category: "Programlama" },
    { name: "Kernel.org", url: "https://www.kernel.org/", color: "#ff7b7b", category: "Programlama" },
    { name: "GNU.org", url: "https://www.gnu.org/", color: "#ff9e64", category: "Programlama" },
    { name: "TLDP", url: "https://tldp.org/", color: "#d7a0ff", category: "Programlama" },
    { name: "Debian Wiki", url: "https://wiki.debian.org/", color: "#ff7898", category: "Programlama" },
    { name: "Ubuntu Docs", url: "https://help.ubuntu.com/", color: "#ff9e64", category: "Programlama" },
    { name: "Fedora Docs", url: "https://docs.fedoraproject.org/", color: "#68d8ff", category: "Programlama" },
    { name: "Linux Journey", url: "https://linuxjourney.com/", color: "#9cf56a", category: "Programlama" },
    { name: "OverTheWire", url: "https://overthewire.org/", color: "#68d8ff", category: "Programlama" },
    { name: "ExplainShell", url: "https://explainshell.com/", color: "#d7a0ff", category: "Programlama" },
    { name: "Linux Survival", url: "https://linuxsurvival.com/", color: "#ff9e64", category: "Programlama" },
    { name: "Crontab.guru", url: "https://crontab.guru/", color: "#ff7b7b", category: "Programlama" },
    { name: "Bash Academy", url: "https://www.bash.academy/", color: "#9cf56a", category: "Programlama" },
    { name: "Linux Handbook", url: "https://linuxhandbook.com/", color: "#68d8ff", category: "Programlama" },
    { name: "Webminal", url: "https://www.webminal.org/", color: "#d7a0ff", category: "Programlama" },
    { name: "Phoronix", url: "https://www.phoronix.com/", color: "#68d8ff", category: "Programlama" },
    { name: "It's FOSS", url: "https://itsfoss.com/", color: "#9cf56a", category: "Programlama" },
    { name: "OMG! Ubuntu!", url: "https://www.omgubuntu.co.uk/", color: "#ff9e64", category: "Programlama" },
    { name: "9to5Linux", url: "https://9to5linux.com/", color: "#ff7b7b", category: "Programlama" },
    { name: "Linux Today", url: "https://www.linuxtoday.com/", color: "#d7a0ff", category: "Programlama" },
    { name: "LWN.net", url: "https://lwn.net/", color: "#9cf56a", category: "Programlama" },
    { name: "Linux Journal", url: "https://www.linuxjournal.com/", color: "#ff7898", category: "Programlama" },
    { name: "FOSS Linux", url: "https://www.fosslinux.com/", color: "#68d8ff", category: "Programlama" },
    { name: "Linux Insider", url: "https://www.linuxinsider.com/", color: "#ff9e64", category: "Programlama" },
    { name: "TecMint", url: "https://www.tecmint.com/", color: "#9cf56a", category: "Programlama" },
    { name: "Unixmen", url: "https://www.unixmen.com/", color: "#d7a0ff", category: "Programlama" },
    { name: "DistroWatch", url: "https://distrowatch.com/", color: "#68d8ff", category: "Programlama" },
    { name: "Linux Mint", url: "https://linuxmint.com/", color: "#70df8e", category: "Programlama" },
    { name: "Ubuntu", url: "https://ubuntu.com/", color: "#ff9e64", category: "Programlama" },
    { name: "Fedora Project", url: "https://fedoraproject.org/", color: "#68d8ff", category: "Programlama" },
    { name: "Arch Linux", url: "https://archlinux.org/", color: "#68d8ff", category: "Programlama" },
    { name: "Debian", url: "https://www.debian.org/", color: "#ff7898", category: "Programlama" },
    { name: "Manjaro", url: "https://manjaro.org/", color: "#70df8e", category: "Programlama" },
    { name: "Pop!_OS", url: "https://pop.system76.com/", color: "#d7a0ff", category: "Programlama" },
    { name: "GitLab", url: "https://about.gitlab.com/", color: "#ff9e64", category: "Programlama" },
    { name: "Docker Hub", url: "https://hub.docker.com/", color: "#68d8ff", category: "Programlama" },
    { name: "Linode", url: "https://www.linode.com/", color: "#9cf56a", category: "Programlama" },
    { name: "DigitalOcean Tutorials", url: "https://www.digitalocean.com/community/tutorials", color: "#68d8ff", category: "Programlama" },
    { name: "Reddit /r/linux", url: "https://www.reddit.com/r/linux/", color: "#ff9e64", category: "Programlama" },
    { name: "Unix & Linux SE", url: "https://unix.stackexchange.com/", color: "#d7a0ff", category: "Programlama" },
    { name: "Ask Ubuntu", url: "https://askubuntu.com/", color: "#ff9e64", category: "Programlama" },
    { name: "Linux Questions", url: "https://www.linuxquestions.org/", color: "#68d8ff", category: "Programlama" },
    { name: "GamingOnLinux", url: "https://www.gamingonlinux.com/", color: "#68d8ff", category: "Programlama" },
    { name: "ProtonDB", url: "https://www.protondb.com/", color: "#9cf56a", category: "Programlama" },
    { name: "GNOME Look", url: "https://www.gnome-look.org/", color: "#d7a0ff", category: "Programlama" },
    { name: "KDE Store", url: "https://store.kde.org/", color: "#68d8ff", category: "Programlama" },
    { name: "Flathub", url: "https://flathub.org/", color: "#9cf56a", category: "Programlama" },
    { name: "Google AI Studio", url: "https://aistudio.google.com/", color: "#68d8ff", category: "AI" },
    { name: "AI Tool", url: "https://datracks.com", color: "#d7a0ff", category: "AI" },
    { name: "Gemini", url: "https://gemini.google.com/", color: "#68d8ff", category: "AI" },
    { name: "ChatGPT", url: "https://chatgpt.com", color: "#9cf56a", category: "AI" },
    { name: "Claude", url: "https://claude.ai", color: "#ff9e64", category: "AI" },
    { name: "Duck.ai", url: "https://duck.ai", color: "#d7a0ff", category: "AI" },
    { name: "Perplexity", url: "https://www.perplexity.ai", color: "#9cf56a", category: "AI" },
    { name: "Leonardo.ai", url: "https://leonardo.ai", color: "#d7a0ff", category: "AI" },
    { name: "Nano Banana", url: "https://aistudio.google.com/models/nano-banana", color: "#d7a0ff", category: "AI" },
    { name: "Ideogram", url: "https://ideogram.ai", color: "#d7a0ff", category: "AI" },
    { name: "Tensor.art", url: "https://tensor.art", color: "#d7a0ff", category: "AI" },
    { name: "Lexica.art", url: "https://lexica.art", color: "#d7a0ff", category: "AI" },
    { name: "BlueWillow", url: "https://www.bluewillow.ai", color: "#d7a0ff", category: "AI" },
    { name: "NightCafe", url: "https://creator.nightcafe.studio", color: "#d7a0ff", category: "AI" },
    { name: "Artbreeder", url: "https://www.artbreeder.com", color: "#d7a0ff", category: "AI" },
    { name: "Deep Dream Generator", url: "https://deepdreamgenerator.com", color: "#d7a0ff", category: "AI" },
    { name: "Prodia", url: "https://app.prodia.com", color: "#d7a0ff", category: "AI" },
    { name: "Kling AI", url: "https://klingai.com", color: "#ff7898", category: "AI" },
    { name: "Captions", url: "https://www.captions.ai", color: "#ff7898", category: "AI" },
    { name: "HeyGen", url: "https://www.heygen.com", color: "#ff7898", category: "AI" },
    { name: "Animaker", url: "https://www.animaker.com", color: "#ff7898", category: "AI" },
    { name: "Unscreen", url: "https://www.unscreen.com", color: "#ff7898", category: "AI" },
    { name: "Opus Clip", url: "https://www.opus.pro", color: "#ff7898", category: "AI" },
    { name: "Wisecut", url: "https://www.wisecut.ai", color: "#ff7898", category: "AI" },
    { name: "Adobe Podcast", url: "https://podcast.adobe.com/enhance", color: "#ff7898", category: "AI" },
    { name: "Fliki", url: "https://fliki.ai", color: "#ff7898", category: "AI" },
    { name: "Steve.ai", url: "https://www.steve.ai", color: "#ff7898", category: "AI" },
    { name: "Copy.ai", url: "https://www.copy.ai", color: "#ff9e64", category: "AI" },
    { name: "Jasper", url: "https://www.jasper.ai", color: "#d7a0ff", category: "AI" },
    { name: "Hemingway", url: "https://hemingwayapp.com", color: "#d7a0ff", category: "AI" },
    { name: "ProWritingAid", url: "https://prowritingaid.com", color: "#d7a0ff", category: "AI" },
    { name: "Smart Copy", url: "https://unbounce.com/product/smart-copy/", color: "#d7a0ff", category: "AI" },
    { name: "Wordtune", url: "https://www.wordtune.com", color: "#d7a0ff", category: "AI" },
    { name: "Readsy", url: "https://readsy.co", color: "#d7a0ff", category: "AI" },
    { name: "Airstory", url: "https://airstory.co", color: "#d7a0ff", category: "AI" },
    { name: "Headline Analyzer", url: "https://coschedule.com/headline-analyzer", color: "#d7a0ff", category: "AI" },
    { name: "Cliche Finder", url: "http://clichefinder.net", color: "#d7a0ff", category: "AI" },
    { name: "CanIRank", url: "https://canirank.com", color: "#d7a0ff", category: "AI" },
    { name: "YandexART", url: "https://ya.ru/art/", color: "#ff6b6b", category: "AI" },
    { name: "NotebookLM", url: "https://notebooklm.google.com/", color: "#68d8ff", category: "AI" },
    { name: "Google Careers", url: "https://careers.google.com/", color: "#68d8ff", category: "Eğitim" },
    { name: "AngelList", url: "https://angel.co", color: "#ff6b6b", category: "Eğitim" },
    { name: "Naukri", url: "https://www.naukri.com", color: "#ff6b6b", category: "Eğitim" },
    { name: "Wellfound", url: "https://wellfound.com", color: "#ff6b6b", category: "Eğitim" },
    { name: "FlexJobs", url: "https://www.flexjobs.com", color: "#ff6b6b", category: "Eğitim" },
    { name: "Levels.fyi", url: "https://www.levels.fyi", color: "#ff6b6b", category: "Eğitim" },
    { name: "Jobscan", url: "https://www.jobscan.co", color: "#ff6b6b", category: "Eğitim" },
    { name: "LinkedIn", url: "https://www.linkedin.com", color: "#ff6b6b", category: "Eğitim" },
    { name: "Indeed", url: "https://www.indeed.com", color: "#ff6b6b", category: "Eğitim" },
    { name: "Glassdoor", url: "https://www.glassdoor.com", color: "#ff6b6b", category: "Eğitim" },
    { name: "MindTools", url: "https://www.mindtools.com", color: "#70df8e", category: "Eğitim" },
    { name: "TED", url: "https://www.ted.com", color: "#70df8e", category: "Eğitim" },
    { name: "Udemy", url: "https://www.udemy.com", color: "#70df8e", category: "Eğitim" },
    { name: "Duolingo", url: "https://www.duolingo.com", color: "#70df8e", category: "Eğitim" },
    { name: "FutureLearn", url: "https://www.futurelearn.com", color: "#70df8e", category: "Eğitim" },
    { name: "Brilliant", url: "https://brilliant.org", color: "#70df8e", category: "Eğitim" },
    { name: "edX", url: "https://www.edx.org", color: "#70df8e", category: "Eğitim" },
    { name: "Coursera", url: "https://www.coursera.org", color: "#70df8e", category: "Eğitim" },
    { name: "Skillshare", url: "https://www.skillshare.com", color: "#70df8e", category: "Eğitim" },
    { name: "Khan Academy", url: "https://www.khanacademy.org", color: "#70df8e", category: "Eğitim" },
    { name: "Grow with Google", url: "https://grow.google/", color: "#68d8ff", category: "Eğitim" },
    { name: "Türkiye Spor Federasyonu", url: "https://www.tssf.gov.tr", color: "#ff9e64", category: "Eğitim" },
    { name: "Photopea", url: "https://www.photopea.com/", color: "#68d8ff", category: "Web Uygulamaları" },
    { name: "Suno Studio", url: "https://suno.com", color: "#d7a0ff", category: "Web Uygulamaları" },
    { name: "Photoskop", url: "https://photoskop.com", color: "#9cf56a", category: "Web Uygulamaları" },
    { name: "Canva", url: "https://www.canva.com", color: "#d7a0ff", category: "Web Uygulamaları" },
    { name: "Notion", url: "https://www.notion.so", color: "#95a8a2", category: "Web Uygulamaları" },
    { name: "Image Edit", url: "https://upperpix.com", color: "#68d8ff", category: "Web Uygulamaları" },
    { name: "Adobe Express", url: "https://www.adobe.com/express/", color: "#68d8ff", category: "Web Uygulamaları" },
    { name: "Figma", url: "https://www.figma.com", color: "#68d8ff", category: "Web Uygulamaları" },
    { name: "Coolors", url: "https://coolors.co", color: "#68d8ff", category: "Web Uygulamaları" },
    { name: "Unsplash", url: "https://unsplash.com", color: "#68d8ff", category: "Web Uygulamaları" },
    { name: "WatermarkRemover", url: "https://www.watermarkremover.io", color: "#68d8ff", category: "Web Uygulamaları" },
    { name: "Flaticon", url: "https://www.flaticon.com", color: "#68d8ff", category: "Web Uygulamaları" },
    { name: "Dribbble", url: "https://dribbble.com", color: "#68d8ff", category: "Web Uygulamaları" },
    { name: "Behance", url: "https://www.behance.net", color: "#68d8ff", category: "Web Uygulamaları" },
    { name: "Spline", url: "https://spline.design", color: "#68d8ff", category: "Web Uygulamaları" },
    { name: "ClickUp", url: "https://clickup.com", color: "#9cf56a", category: "Web Uygulamaları" },
    { name: "Asana", url: "https://asana.com", color: "#9cf56a", category: "Web Uygulamaları" },
    { name: "Cobalt", url: "https://cobalt.tools/", color: "#68d8ff", category: "Web Uygulamaları" },
    { name: "AlternativeTo", url: "https://alternativeto.net/", color: "#d7a0ff", category: "Web Uygulamaları" },
    { name: "Google Groups", url: "https://groups.google.com/", color: "#68d8ff", category: "Forum" },
    { name: "Forum Sinetech", url: "https://forum.sinetech.tr", color: "#ff9e64", category: "Forum" },
    { name: "NSONE", url: "https://negronshow.blogspot.com", color: "#ff9e64", category: "Forum" },
    { name: "TNCTR", url: "https://tnctr.com", color: "#ff9e64", category: "Forum" },
    { name: "BTT", url: "https://btt.community", color: "#ff9e64", category: "Forum" },
    { name: "Simülasyon Türk Park", url: "https://park.simulasyonturk.com/", color: "#ff9e64", category: "Forum" },
    { name: "XDA Forums", url: "https://xdaforums.com", color: "#ff9e64", category: "Forum" },
  ],

  /* Optional centered message. Change enabled to true when you want to show it. */
  popup: {
    enabled: false,
    id: "message-1",
    repeatHours: 24,
    title: "A message for our visitors",
    description: "Add your message here. You can use this space for an announcement, a new service or an important update.",
    link: "https://example.com/",
    buttonText: "Learn more"
  }
};
